### ISSUE TITLE
CSV formating get invalid for songs with 0 plays

### ISSUE THREAD

**Issue by Kiina** [Koster35/playlistExpo_for_Google_Play_Music#1]
Really useful tool, but I noticed some problems. When a song is never played it should probably be a 0, instead it's just missing in the current version.

Just as an example what this looks like:
```
Index,Title,Duration,Artist,Album,Play-count,Rating
"삐삐","3:15","IU","삐삐",Like
```

Also I think the order is wrong. For songs which got played it's (the lower one is sorted as Title, Duration, Artist, Album, Play Count, Random 0 and Rating):
```
Index,Title,Duration,Artist,Album,Play-count,Rating
"삐삐","3:15","IU","삐삐","10",0,Like
```

Is the 0 the index? Because it's zero for every song, maybe i'm just missing something.

Also not sure if fixable, because it seems like random play music behavior but it sometimes lumps instrumentals and the same song on different albums as one, but when exporting them with the tool it gets listed twice:

```
"위아래","3:10","EXID","위아래","14",0,Like
"위아래","3:10","EXID","AH YEAH","14",0,Like
"손대지마","3:25","Ailee","Magazine","3",0,Like
"손대지마 (Instrumental)","3:24","Ailee","Magazine","3",0,Like
```

I never listened to the instrumental and only listened to the other track 14 times, but it keeps exporting both for some reason, but maybe I just need to throw these out by hand....

**Comment by Kiina** [comment]
Okay according to the code it should do it. I think the issue is more with me trying to get the Thumbs up
Auto-playlist, as it doesn't provide any index like other playlists...

**Comment by Koster35** [comment]
Sorry for taking so long to get to this issue!

Auto-generated playlists ('Thumbs up', 'Last added', and 'Free and purchased') now export properly.
